services:
  mongodb:
    image: docker.io/bitnami/mongodb:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=odraw
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081

volumes:
  mongodb_data:
    driver: local